name: Metrics
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: <YOUR_USERNAME>
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi
          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_details: percentage
          plugin_lines: yes
          plugin_followup: yes
          plugin_achievements: yes
